[package]
name = "audio_sim"
version = "0.1.0"
authors = ["kazuma"]
edition = "2018"

[dependencies]
hound = "3.4.0"
clipboard = "0.5"
glium = "0.25"
imgui = "0.1.0-pre"
imgui-glium-renderer = "0.1.0-pre"
imgui-winit-support = "0.1.0-pre"
image = "0.21"